version: '3.8'
services:
  aniworld:
    container_name: aniworld-downloader
    build: .
    ports:
      - "8181:8080"
    volumes:
      - /home/juryi/Media/jellyfinmedia/Anime/:/app/downloads
      - ./data:/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped
